[project]
name = "genx"
version = "0.0.1"
description = "GeneralizationX"
readme = "README.md"
# license = {file = "LICENSE.txt"}
requires-python=">=3.8,<3.12"

dependencies = [
    "gymnasium",
    "robosuite",
    "termcolor",
    "torch",
    "tensorboard",
    "stable_baselines3",
]